default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=.flake8"]
        language: python
        types: [python]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
    - id: nbqa-black
    - id: nbqa-pylint
